config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'articles#index'
  get 'about', to: 'pages#about'
  get 'livre', to: 'articles#livre'
  get 'conference', to: 'articles#conference'
  get 'articles_main', to:'pages#articles_main'
  get 'articles_admin', to:'pages#articles_admin'
  resources :articles
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true;
    validates :description, presence: true;
    validates :category, presence: true;
    # belongs_to :user;
    # validates :user_id, presence: true 
    # before_save { self.email = email.downcase }
end

app/models/user.rb
# class User < ActiveRecord::Base
#     validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
#     validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }
#     has_many :articles
# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    before_action :set_article, only: [:edit, :update, :show, :destroy]

    def set_article
        @article = Article.find(params[:id])
    end

    def new
      @article = Article.new
     end

    def create
        @article = Article.new(article_params)
        if @article.save
         flash[:notice] = "Article was successfully created"
         redirect_to article_path(@article)
        else
         render 'new'
        end
    end

    def show
    end

    def edit
        # @user = User.find(params[:id])
    end

    def update
        if @article.update(article_params)
         flash[:notice] = "Article was updated"
         redirect_to article_path(@article)
        else
         flash[:notice] = "Article was not updated"
         render 'edit'
        end
    end

    def index
        @articles = Article.all
    end

    def destroy
        @article.destroy
        flash[:notice] = "Article was deleted"
        redirect_to articles_path
    end

    private
    def article_params
        params.require(:article).permit(:title, :description, :category, :created_at, :sources, :glossaire)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<div class="row">
 <div class="col-sm-12">
  <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :category %>
   </div>
   <div class="col-sm-6">
    <%= f.text_field :category, class: "form-control", placeholder: "Category of article", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :title %>
   </div>
   <div class="col-sm-6">
    <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :description %>
   </div>
   <div class="col-sm-6">
    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
   </div>
  </div>
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: 'btn btn-primary btn-large' %>
   </div>
  </div>
<% end %>
<%= link_to 'Back', articles_path %>

 </div>
</div>

app/views/articles/_messages.html.erb
<div class="row">
 <div class="col-xs-10 col-xs-offset-1">
  <% flash.each do |name, msg| %>
  <div class='alert alert-<%= "#{name}" %>'>
   <a href="#" class="close" data-dismiss="alert">&#215;</a>
   <%= content_tag :div, msg, :id => "flash_#{name}" is msg.is_a?(String) %>
  </div>
  <% end %>
 </div>
</div>

app/views/articles/articles_admin.html.erb
<div class="container">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">  <%= @article.title %></h1>
        <p class="lead text-justify"> <%= simple_format(@article.description) %></p>
    </div>
</div> 

<h2 align="center">Title: <%= @article.category %></h2> 
<div class="well col-xs-8 col-xs-offset-2">
 <h4 class="center"><strong>Description:</strong></h4>
 <hr>
 <%= simple_format(@article.description)
 <%# <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %> 
 <%# <%= link_to 'Back', articles_path, class: "btn btn-xs btn-success"
 <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger"

app/views/articles/conference.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
   <h1 class="display-4">Les conférences</h1>
   <p class="lead">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It's built with default Bootstrap components and utilities with little customization.</p>
</div>
<div class="container">
   <div class="card-deck mb-3 text-center">
      <div class="card mb-4 box-shadow">
         <div class="card-header" style="background-color:#F85959; border-color:#F85959">
            <h4 class="my-0 font-weight-normal"> Inspiration</h4>
         </div>
         <div class="card-body">
            <h1 class="card-title pricing-card-title">Hackers and Painters</h1>
            <ul class="list-unstyled mt-3 mb-4">
               <li> Paul Graham nous explique la convergence entre l'artiste et le developpeur </li>
            </ul>
            <button type="button" class="btn btn-lg btn-block btn-outline-primary" style="color:#F85959; border-color:#F85959">Lire l'article</button>
         </div>
      </div>
      <div class="card mb-4 box-shadow">
         <div class="card-header" style="background-color:#F85959; border-color:#F85959">
            <h4 class="my-0 font-weight-normal style="background-color:#F85959; border-color:#F85959""> Intelligence Artificielle</h4>
         </div>
         <div class="card-body">
            <h1 class="card-title pricing-card-title">Superpaths and danger</h1>
            <ul class="list-unstyled mt-3 mb-4">
               <li> Paul Graham nous explique la convergence entre l'artiste et le developpeur </li>
            </ul>
            <button type="button" class="btn btn-lg btn-block btn-outline-primary"style="color:#F85959; border-color:#F85959">Lire l'article</button>
         </div>
      </div>
      <div class="card mb-4 box-shadow">
         <div class="card-header" style="background-color:#F85959; border-color:#F85959">
            <h4 class="my-0 font-weight-normal">Growth Hacking</h4>
         </div>
         <div class="card-body">
            <h1 class="card-title pricing-card-title">GrowHacking blabla</h1>
            <ul class="list-unstyled mt-3 mb-4">
               <li>Paul Graham nous explique la convergence entre l'artiste et le developpeur</li>
            </ul>
            <button type="button" class="btn btn-lg btn-block btn-outline-primary" style="color:#F85959; border-color:#F85959">Lire l'article</button>
         </div>
      </div>
   </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<% if @article.errors.any? %>
 <h2>The following errors prevented the article from saving:</h2>
 <ul>
 <% @article.errors.full_messages.each do |msg|%>
 <li><%= msg %></li>
 <% end %>
 </ul>
<% end %>
<%= form_for @article do |f| %>
 <p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
 </p>
 <p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
 </p>
 <p>
  <%= f.submit %>
 </p>
<% end %>

app/views/articles/index.html.erb
<%# <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
   <h1 class="display-4">Les livres </h1>
   <p class="lead">Tempor id cupidatat officia esse ipsum laboris eiusmod.</p>
</div> %>

<section class="jumbotron text-center">
   <h1 class="jumbotron-heading">La curiosité est un joli défaut</h1>
   <br>
   <br>
   <!-- <p class="lead">
      "L’important est de ne jamais s’arrêter de se questionner, la curiosité a sa propre raison d’exister"
      <br> Albert Einstein</p>
      </p> -->
   <!-- <div class="container">
      <div class="btn btn-secondary my-2" style="background-color:white;color:#F85959; border-color:#F85959">
         <%= link_to 'livre','livre', :class => "btn-main" %> 
      </div>
      <div class="btn btn-secondary my-2" style="background-color:white;color:#F85959; border-color:#F85959">
         <%= link_to 'conference','conference', :class => "btn-main" %>
      </div>
   </div>-->
</section>

<div class="d-flex align-items-start">
    <div class="container">
        <div class="row">
        <% @articles.each do |article| %>
            <div class="card-deck col-md-4 text-center">
                <div class="card mb-4 box-shadow">
                    <div class="card-header" style="background-color:#F85959; border-color:#F85959">
                        <h4 class="my-0 font-weight-normal category_btn"> <%= link_to article.category, article_path(article) %></h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">     <%= link_to article.short_title, article_path(article) %></h1>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>  <%= truncate(article.short_description, length: 150) %></li>
                        </ul>
                        <%# <button type="button" class="btn btn-lg btn-block btn-outline-primary" style="color:#F85959; border-color:#F85959">Lire l'article</button> %>
                        <div class="btn btn-lg btn-block btn-outline article_btn">
                            <%= link_to "Lire l'article", article_path(article),  :class => "btn-main fixed"  %>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
        </div>
    </div>
</div>

app/views/articles/livre.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
   <h1 class="display-4">Les livres </h1>
   <p class="lead">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It's built with default Bootstrap components and utilities with little customization.</p>
</div>
<div class="container">
   <div class="card-deck mb-3 text-center">
      <div class="card mb-4 box-shadow">
         <div class="card-header" style="background-color:#F85959; border-color:#F85959">
            <h4 class="my-0 font-weight-normal"> Inspiration</h4>
         </div>
         <div class="card-body">
            <h1 class="card-title pricing-card-title">Hackers and Painters</h1>
            <ul class="list-unstyled mt-3 mb-4">
               <li> Paul Graham nous explique la convergence entre l'artiste et le developpeur </li>
            </ul>
            <%# <button type="button" class="btn btn-lg btn-block btn-outline-primary" style="color:#F85959; border-color:#F85959">Lire l'article</button> %>
            <div class="btn btn-lg btn-block btn-outline-primary" style="color:#F85959; border-color:#F85959">
            <%= link_to "Lire l'article","articles_main", :class => "btn-main" %> |
      </div>
         </div>
      </div>
      <div class="card mb-4 box-shadow">
         <div class="card-header" style="background-color:#F85959; border-color:#F85959">
            <h4 class="my-0 font-weight-normal style="background-color:#F85959; border-color:#F85959""> Intelligence Artificielle</h4>
         </div>
         <div class="card-body">
            <h1 class="card-title pricing-card-title">Superpaths and danger</h1>
            <ul class="list-unstyled mt-3 mb-4">
               <li> Paul Graham nous explique la convergence entre l'artiste et le developpeur </li>
            </ul>
            <button type="button" class="btn btn-lg btn-block btn-outline-primary"style="color:#F85959; border-color:#F85959">Lire l'article</button>
         </div>
      </div>
      <div class="card mb-4 box-shadow">
        <div class="card-header" style="background-color:#F85959; border-color:#F85959">
            <h4 class="my-0 font-weight-normal">Growth Hacking</h4>
        </div>
        <div class="card-body">
            <h1 class="card-title pricing-card-title">GrowHacking blabla</h1>
            <ul class="list-unstyled mt-3 mb-4">
               <li>Paul Graham nous explique la convergence entre l'artiste et le developpeur</li>
            </ul>
            <button type="button" id="article" class="btn btn-lg btn-block btn-outline-primary" style="color:#F85959; border-color:#F85959">Lire l'article</button>
        </div>
      </div>
   </div>
</div>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="container">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h2 class="display-10 category_title">  <%= @article.category %></h2>
        <br>
        <h1 class="display-6">  <%= @article.title %></h1>
        <img src="https://synbioz-website-attachments.s3.eu-west-1.amazonaws.com/articles/20170928/Jim%20Weirich_thumb_450.png">
    </div>
    <p class="lead text-justify"> <%= simple_format(@article.description) %></p>
    <%# <p class="lead text-justify" style="color:#F85959"> Glossaire: <br></p> <a> <%= @article.glossaire %></a>
    <p class="lead text-justify" style="color:#F85959"> Sources: <br></p> <a> <%= @article.sources %></a>
    <p class="lead text-justify" style="color:#F85959"> Article créé le <%= @article.created_at %> par Laure Peu </p>
</div> 

<%# <h2 align="center">Title: <%= @article.category %></h2> 
<%# <div class="well col-xs-8 col-xs-offset-2">
 <h4 class="center"><strong>Description:</strong></h4>
 <hr>
 <%= simple_format(@article.description) %>
 <%# <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %> 
 <%# <%= link_to 'Back', articles_path, class: "btn btn-xs btn-success" %>
 <%# <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>

app/views/layouts/_footer.html.erb
<div class="footer">
            <div class="footer-links">
              <a href="https://github.com/laurepeu" target="_blank"><i class="fab fa-github"></i></a>
              <a href="https://medium.com/@laurepeu" target="_blank"><i class="fab fa-medium"></i></a>
              <a href="https://www.linkedin.com/in/laurepeucelle/" target="_blank"><i class="fab fa-linkedin"></i></a>
            </div>
            <div class="footer-copyright">
              Ce site est créé avec  <i class="fa fa-heart"></i> par Laure PEU
            </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-2 col-md-2 py-4">
        <%= image_tag "bitmojilaure" , size: "100", alt: "Laure Peucelle" %>
      </div>    
      <div class="col-sm-6 col-md-6 py-4">
        <h4 class="text-white">Salut, moi c est Laure !</h4>
        <a href="#" class="text-white">      Envoyez moi un message  <i class="fas fa-envelope" ></i></a>
      </div>
      <div class="col-sm-6 py-4">
      <p class="text-muted"> 

      <%# <br>
      <br> Je profite de mes oreilles en allant à des conférences
      <br> Je profite de mes yeux en lisant
      <br> Je profite de mes doigts pour tout vous raconter. %>
    </p>
      </div>
    </div>
  </div>
</div>
<div class="navbar navbar-light" style="background-color:#F85959">
  <div class="container d-flex justify-content-between">
  <%= link_to root_path do %>
  <%= image_tag "nuk", alt: "rasberry" %>
  <% end %>
      <strong><i class="fas fa-bullhorn"></i>  Now You Know</strong>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Now U Know</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="description" content="Des informations; conseils; tech;html;fille;css;rasbperry;livres;conférences;lille;paris;autoentrepreneur;test;coder;geek;tech">
    <meta name="author" content="Laure Peucelle">
    <link rel="icon" href="nuk-small.ico">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <!-- Font awesome --> 
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  </head>

  <body>
  <%= render 'layouts/navigation' %>
    <%= yield %>
  <%= render 'layouts/footer' %>
  <%# <%= debug(params) if Rails.env.development? %>
  </body>

</html>

app/views/pages/about.html.erb
<h1>About Blog</h1>
<%= link_to 'Home', root_path %>

app/views/pages/articles_main.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
   <h1 class="display-4">  Mollit eu Lorem irure fugiat offi cillum.</h1>
   <p class="lead text-justify">Fugiat consectetur sint sunt deserunt. Eu et in commodo non. Ea eu eiusmod deserunt anim minim ad fugiat nulla ipsum incididunt do reprehenderit pariatur. Exercitation incididunt consectetur irure mollit qui pariatur est anim amet aliquip. Magna consequat veniam elit excepteur qui veniam quis amet dolore aliquip.

Cillum laboris enim voluptate mollit ullamco ullamco proident nulla ullamco id adipisicing. Do mollit dolore occaecat enim cillum proident. Consequat anim anim id enim veniam aute in ipsum excepteur excepteur in. Consectetur aliqua in consequat pariatur velit mollit esse adipisicing velit.

Mollit proident occaecat ut commodo minim id culpa amet ut dolore sint veniam pariatur nisi. Est aliquip quis labore aliqua ex laborum ipsum amet veniam Lorem commodo. Velit ullamco cillum aliqua aliqua irure velit laboris consequat. Et duis esse aliqua esse voluptate occaecat in voluptate et. Voluptate consectetur id consequat ut qui consectetur et ad cillum. Sit amet ex quis esse consectetur sint nostrud elit.

Magna anim velit minim culpa sint do veniam. Voluptate ut ad do cupidatat irure cupidatat sit ad deserunt laboris nostrud officia amet ex. Eiusmod eu elit ullamco enim anim exercitation. Velit anim deserunt Lorem reprehenderit velit.</p>
</div>
<div class="container">
</div> 

app/views/pages/index.html.erb
<%# <%= link_to 'About', about_path %>

<section class="jumbotron text-center">
   <h1 class="jumbotron-heading">La curiosité est un joli défaut</h1>
   <br>
   <br>
   <!-- <p class="lead">
      "L’important est de ne jamais s’arrêter de se questionner, la curiosité a sa propre raison d’exister"
      <br> Albert Einstein</p>
      </p> -->
   <div class="container">
      <div class="btn btn-secondary my-2" style="background-color:white;color:#F85959; border-color:#F85959">
         <%= link_to 'livre','livre', :class => "btn-main" %> 
      </div>
      <div class="btn btn-secondary my-2" style="background-color:white;color:#F85959; border-color:#F85959">
         <%= link_to 'conference','conference', :class => "btn-main" %>
      </div>
   </div>
</section>
<div class="album py-5 bg-light">
<div class="container">
   <div class="row">
      <div class="col-md-4">
         <div class="card mb-4 box-shadow">
           <%= image_tag "raspberry" , size: "225px", alt: "rasberry" %>
            <div class="card-body">
               <p class="card-text"> Test : Créer son propre serveur avec une Rasberry Pie 3</p>
               <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                     <button type="button"  class="btn btn-sm btn-outline-secondary" style="color:#F85959; border-color:#F85959">View</button>
                     <button type="button" class="btn btn-sm btn-outline-secondary" style="color:#F85959; border-color:#F85959">Like</button>
                  </div>
                  
                  <small class="text-muted">9 mins</small>
               </div>
            </div>
         </div>
      </div>
      <div class="col-md-4">
         <div class="card mb-4 box-shadow">
            <%= image_tag "raspberry" , size: "225px", alt: "rasberry" %>
            <div class="card-body">
               <p class="card-text"> Conférence : l Intelligence Artificielle vu par Microsoft</p>
               <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                     <button type="button" class="btn btn-sm btn-outline-secondary"style="color:#F85959; border-color:#F85959">View</button>
                     <button type="button" class="btn btn-sm btn-outline-secondary"style="color:#F85959; border-color:#F85959">Like</button>
                  </div>
                  <small class="text-muted">9 mins</small>
               </div>
            </div>
         </div>
      </div>
      <div class="col-md-4">
         <div class="card mb-4 box-shadow">
             <%= image_tag "raspberry" , size: "225px", alt: "rasberry" %>
            <div class="card-body">
               <p class="card-text">Livre : Hackers & Painters de Paul Graham</p>
               <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                     <button type="button" class="btn btn-sm btn-outline-secondary"style="color:#F85959; border-color:#F85959">View</button>
                     <button type="button" class="btn btn-sm btn-outline-secondary"style="color:#F85959; border-color:#F85959">Like</button>
                  </div>
                  <small class="text-muted">9 mins</small>
               </div>
            </div>
         </div>
      </div>
  
      </div>
   </div>
</div>

app/views/shared/called _errors.html.erb
<% if obj.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(obj.errors.count, "error") %>
      prohibited this object from being saved:
     </h2>
     <div class="panel-body">
      <ul>
       <% obj.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>